### ISSUE TITLE
missing qt-raspberrypi-configuration

### ISSUE THREAD

**Issue by iztoogood** [opencardev/prebuilts#5]
in prebuilts/buildsystem/ scripts
about steps 4_build_qt5-12.sh

before line 26 (`cd $HOME/qt-raspberrypi-configuration`)

look like if missing a step :
something like :
git clone https://github.com/oniongarlic/qt-raspberrypi-configuration.git

... or i have missed a something...

**Comment by iztoogood** [comment]
What about the config flag -qt-pcre ... is it really necessary ?

**Comment by alexbeatle** [comment]
> in prebuilts/buildsystem/ scripts
> about steps 4_build_qt5-12.sh
> 
> before line 26 (`cd $HOME/qt-raspberrypi-configuration`)
> 
> look like if missing a step :
> something like :
> git clone https://github.com/oniongarlic/qt-raspberrypi-configuration.git
> 
> ... or i have missed a something...

before line 26 added:
_cd $HOME
rm -rf qt-raspberrypi-configuration
git clone https://github.com/oniongarlic/qt-raspberrypi-configuration.git_

But in the end "make" still fails.

`
mv -f libcomposeplatforminputcontextplugin.so ../../../../plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
make[5]: Leaving directory '/home/pi/qt512_build/qtbase/src/plugins/platforminputcontexts/compose'
make[4]: Leaving directory '/home/pi/qt512_build/qtbase/src/plugins/platforminputcontexts'
make[3]: Leaving directory '/home/pi/qt512_build/qtbase/src/plugins'
Makefile:723: recipe for target 'sub-plugins-make_first' failed
make[2]: *** [sub-plugins-make_first] Error 2
make[2]: Leaving directory '/home/pi/qt512_build/qtbase/src'
Makefile:50: recipe for target 'sub-src-make_first' failed
make[1]: *** [sub-src-make_first] Error 2
make[1]: Leaving directory '/home/pi/qt512_build/qtbase'
Makefile:83: recipe for target 'module-qtbase-make_first' failed
make: *** [module-qtbase-make_first] Error 2
make failed
`

Any suggestions?

Tried using:
https://www.tal.org/tutorials/building-qt-512-raspberry-pi
and
https://www.qtcentre.org/threads/26712-error-error-quot-Not-supported-ARM-architecture-quot

But still no go.

**Comment by matt2005** [comment]
Please retry using latest instructions
